version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: ./compose/local/fastapi/Dockerfile
        image: fastapi_web
        
        command: /start
        volumes:
            - .:/app
        ports:
            - 8000:8000
        env_file: 
            - ./.env/.dev-sample
        depends_on: 
            - redis
    
    redis:
        container_name: redis
        image: redis:6.2-alpine
    
    celery_worker:
        build: 
            context: .
            dockerfile: ./compose/local/fastapi/Dockerfile
        image: fastapi_celery_worker
        command: /start-celeryworker
        volumes:
            - .:/app
    
        env_file: 
            - ./.env/.dev-sample
        depends_on:
            - redis
            - web
